#!/bin/bash

getLocalIP()
  if nmcli con show | grep "tun0" > /dev/null ; then
  # Use VPN interface
    echo `/sbin/ifconfig tun0 | grep -i mask | awk '{print $2}'| cut -f2 -d:`

  else
  # No VPN interface
    if nmcli con show | grep "wlo1" > /dev/null ; then
      echo `/sbin/ifconfig wlo1 | grep -i mask | awk '{print $2}'| cut -f2 -d:`
    else
  # Use VPN interface
      echo `/sbin/ifconfig eno1 | grep -i mask | awk '{print $2}'| cut -f2 -d:`
    fi
  fi

getLocalIP
